# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'options.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialogButtonBox, QFontComboBox,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QSlider, QSpinBox, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(316, 367)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QSize(500, 500))
        MainWindow.setBaseSize(QSize(500, 500))
        icon = QIcon()
        icon.addFile(u"icon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.button_box = QDialogButtonBox(self.centralwidget)
        self.button_box.setObjectName(u"button_box")
        self.button_box.setGeometry(QRect(90, 310, 156, 24))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.button_box.sizePolicy().hasHeightForWidth())
        self.button_box.setSizePolicy(sizePolicy2)
        self.button_box.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.button_box.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.opacity_label = QLabel(self.centralwidget)
        self.opacity_label.setObjectName(u"opacity_label")
        self.opacity_label.setGeometry(QRect(20, 63, 44, 22))
        self.file_name_edit = QLineEdit(self.centralwidget)
        self.file_name_edit.setObjectName(u"file_name_edit")
        self.file_name_edit.setGeometry(QRect(105, 9, 201, 22))
        self.file_name_edit.setAutoFillBackground(False)
        self.file_name_edit.setReadOnly(True)
        self.file_name_label = QLabel(self.centralwidget)
        self.file_name_label.setObjectName(u"file_name_label")
        self.file_name_label.setGeometry(QRect(20, 9, 56, 22))
        self.text_label = QLabel(self.centralwidget)
        self.text_label.setObjectName(u"text_label")
        self.text_label.setGeometry(QRect(20, 36, 24, 22))
        self.text_edit = QLineEdit(self.centralwidget)
        self.text_edit.setObjectName(u"text_edit")
        self.text_edit.setGeometry(QRect(105, 36, 201, 22))
        self.density_label = QLabel(self.centralwidget)
        self.density_label.setObjectName(u"density_label")
        self.density_label.setGeometry(QRect(20, 90, 42, 22))
        self.font_scale_label = QLabel(self.centralwidget)
        self.font_scale_label.setObjectName(u"font_scale_label")
        self.font_scale_label.setGeometry(QRect(20, 130, 71, 22))
        self.font_scale_spinbox = QSpinBox(self.centralwidget)
        self.font_scale_spinbox.setObjectName(u"font_scale_spinbox")
        self.font_scale_spinbox.setGeometry(QRect(110, 130, 51, 22))
        self.font_scale_spinbox.setMinimum(1)
        self.font_scale_spinbox.setMaximum(300)
        self.font_scale_spinbox.setSingleStep(10)
        self.font_scale_spinbox.setValue(90)
        self.font_scale_spinbox.setDisplayIntegerBase(10)
        self.font_name_label = QLabel(self.centralwidget)
        self.font_name_label.setObjectName(u"font_name_label")
        self.font_name_label.setGeometry(QRect(20, 170, 71, 22))
        self.font_selector = QFontComboBox(self.centralwidget)
        self.font_selector.setObjectName(u"font_selector")
        self.font_selector.setGeometry(QRect(70, 170, 184, 22))
        self.font_selector.setDuplicatesEnabled(False)
        self.font_selector.setModelColumn(0)
        self.font_selector.setFontFilters(QFontComboBox.FontFilter.AllFonts)
        font = QFont()
        font.setFamilies([u"Arial"])
        self.font_selector.setCurrentFont(font)
        self.color_label = QLabel(self.centralwidget)
        self.color_label.setObjectName(u"color_label")
        self.color_label.setGeometry(QRect(20, 210, 71, 22))
        self.color_edit = QLineEdit(self.centralwidget)
        self.color_edit.setObjectName(u"color_edit")
        self.color_edit.setGeometry(QRect(150, 210, 101, 22))
        self.color_edit.setMaxLength(11)
        self.color_edit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.color_edit.setClearButtonEnabled(False)
        self.color_pick_button = QPushButton(self.centralwidget)
        self.color_pick_button.setObjectName(u"color_pick_button")
        self.color_pick_button.setGeometry(QRect(70, 210, 75, 24))
        self.angle_label = QLabel(self.centralwidget)
        self.angle_label.setObjectName(u"angle_label")
        self.angle_label.setGeometry(QRect(20, 250, 71, 22))
        self.angle_slider = QSlider(self.centralwidget)
        self.angle_slider.setObjectName(u"angle_slider")
        self.angle_slider.setGeometry(QRect(70, 250, 181, 22))
        self.angle_slider.setMinimum(-90)
        self.angle_slider.setMaximum(90)
        self.angle_slider.setSingleStep(10)
        self.angle_slider.setValue(-10)
        self.angle_slider.setTracking(True)
        self.angle_slider.setOrientation(Qt.Orientation.Horizontal)
        self.angle_slider.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.angle_slider.setTickInterval(10)
        self.density_slider = QSlider(self.centralwidget)
        self.density_slider.setObjectName(u"density_slider")
        self.density_slider.setGeometry(QRect(100, 90, 101, 22))
        self.density_slider.setMinimum(1)
        self.density_slider.setMaximum(200)
        self.density_slider.setValue(80)
        self.density_slider.setOrientation(Qt.Orientation.Horizontal)
        self.density_slider.setInvertedAppearance(False)
        self.density_slider.setInvertedControls(False)
        self.density_slider.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.density_slider.setTickInterval(50)
        self.density_edit = QLineEdit(self.centralwidget)
        self.density_edit.setObjectName(u"density_edit")
        self.density_edit.setGeometry(QRect(210, 90, 41, 22))
        self.angle_edit = QLineEdit(self.centralwidget)
        self.angle_edit.setObjectName(u"angle_edit")
        self.angle_edit.setGeometry(QRect(260, 250, 31, 22))
        self.opacity_slider = QSlider(self.centralwidget)
        self.opacity_slider.setObjectName(u"opacity_slider")
        self.opacity_slider.setGeometry(QRect(100, 60, 101, 22))
        self.opacity_slider.setMinimum(1)
        self.opacity_slider.setMaximum(100)
        self.opacity_slider.setSingleStep(10)
        self.opacity_slider.setValue(20)
        self.opacity_slider.setOrientation(Qt.Orientation.Horizontal)
        self.opacity_slider.setInvertedAppearance(False)
        self.opacity_slider.setInvertedControls(False)
        self.opacity_slider.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.opacity_slider.setTickInterval(10)
        self.opacity_edit = QLineEdit(self.centralwidget)
        self.opacity_edit.setObjectName(u"opacity_edit")
        self.opacity_edit.setGeometry(QRect(210, 60, 41, 22))
        self.opacity_edit.setEchoMode(QLineEdit.EchoMode.Normal)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Watermarking", None))
        self.opacity_label.setText(QCoreApplication.translate("MainWindow", u"Opacity:", None))
        self.file_name_label.setText(QCoreApplication.translate("MainWindow", u"File Name:", None))
        self.text_label.setText(QCoreApplication.translate("MainWindow", u"Text:", None))
        self.density_label.setText(QCoreApplication.translate("MainWindow", u"Density:", None))
        self.font_scale_label.setText(QCoreApplication.translate("MainWindow", u"Font Scale:", None))
        self.font_name_label.setText(QCoreApplication.translate("MainWindow", u"Font:", None))
        self.font_selector.setCurrentText(QCoreApplication.translate("MainWindow", u"Arial", None))
        self.font_selector.setPlaceholderText("")
        self.color_label.setText(QCoreApplication.translate("MainWindow", u"Color:", None))
        self.color_edit.setInputMask(QCoreApplication.translate("MainWindow", u"999,999,999", None))
        self.color_edit.setText(QCoreApplication.translate("MainWindow", u"255,255,255", None))
        self.color_pick_button.setText(QCoreApplication.translate("MainWindow", u"Pick Color", None))
        self.angle_label.setText(QCoreApplication.translate("MainWindow", u"Angle:", None))
        self.density_edit.setInputMask(QCoreApplication.translate("MainWindow", u"0000", None))
        self.density_edit.setText(QCoreApplication.translate("MainWindow", u"90", None))
        self.angle_edit.setText(QCoreApplication.translate("MainWindow", u"-10", None))
        self.opacity_edit.setInputMask(QCoreApplication.translate("MainWindow", u"#.##", None))
        self.opacity_edit.setText(QCoreApplication.translate("MainWindow", u"0.25", None))
    # retranslateUi

